/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Calf {
  'id' : bigint,
  'birthDate' : string,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'photoUrl' : [] | [string],
  'gender' : string,
  'notes' : [] | [string],
  'motherCowId' : bigint,
}
export interface Cow {
  'id' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'photoUrl' : [] | [string],
  'breed' : [] | [string],
}
export interface HeatRecord {
  'id' : bigint,
  'month' : string,
  'ownerId' : Principal,
  'date' : string,
  'createdAt' : bigint,
  'cowId' : bigint,
  'notes' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCalf' : ActorMethod<
    [string, string, string, bigint, [] | [string], [] | [string]],
    bigint
  >,
  'addCow' : ActorMethod<[string, [] | [string], [] | [string]], bigint>,
  'addHeatRecord' : ActorMethod<
    [bigint, string, string, [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCalf' : ActorMethod<[bigint], undefined>,
  'deleteCow' : ActorMethod<[bigint], undefined>,
  'deleteHeatRecord' : ActorMethod<[bigint], undefined>,
  'getCalf' : ActorMethod<[bigint], Calf>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCow' : ActorMethod<[bigint], Cow>,
  'getCowHeatRecords' : ActorMethod<[bigint], Array<HeatRecord>>,
  'getHeatRecord' : ActorMethod<[bigint], HeatRecord>,
  'getMyCalves' : ActorMethod<[], Array<Calf>>,
  'getMyCows' : ActorMethod<[], Array<Cow>>,
  'getMyHeatRecords' : ActorMethod<[], Array<HeatRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCalf' : ActorMethod<
    [bigint, string, string, string, bigint, [] | [string], [] | [string]],
    undefined
  >,
  'updateCow' : ActorMethod<
    [bigint, string, [] | [string], [] | [string]],
    undefined
  >,
  'updateHeatRecord' : ActorMethod<
    [bigint, bigint, string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];